name: Greet first-time contributors

on:
  pull_request:
    branches:
    - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Hello and thank you for raising this issue.'
          pr-message: 'Hi, Thank you for your contribution.'
